-- PWA Learning Report V1 schema
create table if not exists public.classes (
  id text primary key,
  name text not null unique
);

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  name text not null,
  class_id text not null references public.classes(id) on update cascade
);

create table if not exists public.teachers (
  id bigint generated by default as identity primary key,
  name text not null,
  email text unique,
  role text not null default 'teacher' check (role in ('admin','teacher'))
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table if not exists public.teacher_subjects (
  teacher_id bigint not null references public.teachers(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  primary key (teacher_id, subject_id)
);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  attendance_date date not null,
  session text not null check (session in ('shubuh','maghrib','isya')),
  class_id text not null references public.classes(id),
  subject_id bigint not null references public.subjects(id),
  student_id bigint not null references public.students(id) on delete cascade,
  present boolean not null default false,
  recorded_by bigint references public.teachers(id),
  created_at timestamptz not null default now(),
  unique(attendance_date, session, class_id, subject_id, student_id)
);

alter table public.classes enable row level security;
alter table public.students enable row level security;
alter table public.teachers enable row level security;
alter table public.subjects enable row level security;
alter table public.teacher_subjects enable row level security;
alter table public.attendance enable row level security;

-- Initial V1 policy: authenticated users may read/write attendance and reference data.
-- Tighten policies by teacher assignment before production rollout.
create policy "authenticated read classes" on public.classes for select to authenticated using (true);
create policy "authenticated read students" on public.students for select to authenticated using (true);
create policy "authenticated read teachers" on public.teachers for select to authenticated using (true);
create policy "authenticated read subjects" on public.subjects for select to authenticated using (true);
create policy "authenticated read teacher subjects" on public.teacher_subjects for select to authenticated using (true);
create policy "authenticated read attendance" on public.attendance for select to authenticated using (true);
create policy "authenticated insert attendance" on public.attendance for insert to authenticated with check (true);
create policy "authenticated update attendance" on public.attendance for update to authenticated using (true) with check (true);
